travis:
  secure:
    BINSTAR_TOKEN: wNeZ2r7PLTi16M4XjAFebmWMCKRCquy3YpNLrsIeJ+itlCiK/3WaYOSDUTWrgBAocEowBvpGqCnpoCH2RYi1UexaUMqBS5524bSJSdyUOCoTEbDz7adQPM9q26WTJnYqLzaA0zDhWW7Jd200RfjMr/gvCe6tWZnooTZdutJTStzqGAZC7rbzXHD974DfTlFFgF4d6N8v15AcBD/0UAOtNAtGlJByRdyrLriOsBsiyJo37+LWhdlPHyXQA4WyYHAE5gcYLuHpgpkAPpkFjBKF2/RG44N7d3vA27j6pPNvHCjpGNIUuVE2htYBaKn1Ws5QlokhMraMo332FQwsGFrL6QLQnq7D7iqj1P1yFAA6NYNfeSD3tSecaS8zoJ4opZEdErkwFk8FhJiNwiczB3Wr4paJsSWw1ebr5tv3RyrvKWLXrfTn6L3frJbmNmwlu9rEaY3sl8noSiyzI4s/Pj15rY8R4XDal18m3FWsOqR3tSQQO/elyLb3Dy2JDzBGqUxlJ6z3B8hFiQczeTaxmyUFwxqhazrHsZDki4KklxZX28jYpW50WGyvODyA8c4+Mh3EDDRSVK80hE+4r4NYLiIfK797HAdr+Zi1S6UzayFpQiv79YsksRE6WnfFtvoHfpK9vahzjXCaV2oqMOA31INOFK3Po/+TSmsK8zmuRHsAmAc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
